apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  namespace: bluegreen
  labels:
    app: wezva-app
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wezva-app
      version: blue
  template:
    metadata:
      labels:
        app: wezva-app
        version: blue
    spec:
      containers:
        - name: wezva-app
          image: badhonparvej481/wezva-app:v1
          ports:
            - containerPort: 31339
